#!/usr/bin/env bash

#
# This command generates the scaffoldings...
#
# it generates files such as...
#
# - grails-app/services/com/kei/????Service.groovy
# - grails-app/controllers/com/kei/????Controller.groovy
# - src/integration-test/groovy/com/kei/????ServiceSpec.groovy
# - src/test/groovy/com/kei/????ControllerSpec.groovy
#

for x in $@
do
    if [ -z $x ]; then
        printf "\nYou need argument such as: [com.xxx.yyy.Bbbb]\n\n"
        continue
    fi

    if [[ ! $x =~ ^([a-zA-Z\.]+)+([.]+)([a-zA-Z]+)+$ ]]; then
        printf "\nNamespace is not correct\n\n"
        continue
    fi

    grails generate-controller $x
done
