#!/usr/bin/env bash

if [ -z $1 ]; then
    printf "\nYou need argument such as: [com.xxx.yyy.Bbbb]\n\n"
    exit
fi

if [[ ! $1 =~ ^([a-zA-Z\.]+)+([a-zA-Z]+)+$ ]]; then
    printf "\nNamespace is not correct\n\n"
    exit
fi

grails create-domain-class $1 
